<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Passwords.Client</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\Roblox.Http.ServiceClient\Roblox.Http.ServiceClient.csproj" />
    <ProjectReference Include="..\Instrumentation\Roblox.Instrumentation\Roblox.Instrumentation.csproj" />
    <ProjectReference Include="..\Roblox.RequestContext\Roblox.RequestContext.csproj" />
    <ProjectReference Include="..\Roblox.Http.Client\Roblox.Http.Client.csproj" />
    <ProjectReference Include="..\Caching\Roblox.Caching\Roblox.Caching.csproj" />
    <ProjectReference Include="..\Configuration\Roblox.Configuration\Roblox.Configuration.csproj" />
    <ProjectReference Include="..\Sentinels\Roblox.Sentinels\Roblox.Sentinels.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
</Project>