<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Common.Web</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Core" />
    <ProjectReference Include="..\\..\\Diagnostics\\Roblox.Diagnostics\\Roblox.Diagnostics.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox.Common\\Roblox.Common.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Platform\\Infrastructure\\Roblox.Platform.Infrastructure\\Roblox.Platform.Infrastructure.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Web\\Roblox.WebsiteSettings\\Roblox.WebsiteSettings.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Owin" Version="4.2.2" />
  </ItemGroup>
</Project>