<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Entities.Mssql</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoWarn>$(NoWarn);0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <!-- Version is centralized in Directory.Build.props -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\Mssql\\Roblox.MssqlDatabases\\Roblox.MssqlDatabases.csproj" />
    <ProjectReference Include="..\\..\\Data\\Roblox.Data\\Roblox.Data.csproj" />
  </ItemGroup>
</Project>