<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.Thumbs</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Stubs\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Roblox.Thumbs.AssetImage.js" />
    <None Remove="Roblox.Thumbs.AvatarImage.js" />
    <None Remove="Roblox.Thumbs.Image.js" />
    <EmbeddedResource Include="Roblox.Thumbs.AssetImage.js" LogicalName="Roblox.Thumbs.AssetImage.js" />
    <EmbeddedResource Include="Roblox.Thumbs.AvatarImage.js" LogicalName="Roblox.Thumbs.AvatarImage.js" />
    <EmbeddedResource Include="Roblox.Thumbs.Image.js" LogicalName="Roblox.Thumbs.Image.js" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Core" />
    <ProjectReference Include="..\\..\\Thumbnails\\Roblox.Platform.Thumbnails.RequestValidation\\Roblox.PlatformThumbnails.RequestValidation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Common\\Roblox.Common.Web\\Roblox.Common.Web.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Badges\\Roblox.Platform.Badges\\Roblox.Platform.Badges.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.Assets\\Roblox.Platform.Assets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Universes\\Roblox.Platform.Universes\\Roblox.Platform.Universes.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership\\Roblox.Platform.Membership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Outfits\\Roblox.Platform.Outfits\\Roblox.Platform.Outfits.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Controls\\Roblox.Controls\\Roblox.Controls.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\FloodCheckers\\Roblox.FloodCheckers\\Roblox.FloodCheckers.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Locking\\Roblox.Locking\\Roblox.Locking.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Avatar\\Roblox.Platform.Avatar\\Roblox.Platform.Avatar.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Amazon\\Roblox.Amazon.Sqs\\Roblox.Amazon.Sqs.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Thumbnails\\Roblox.Platform.Thumbnails.Repository\\Roblox.Platform.Thumbnails.Repository.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Content\\Roblox.Platform.ContentFilter.Client\\Roblox.Platform.ContentFilter.Client.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.AssetsCore\\Roblox.Platform.AssetsCore.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Website\\Roblox.WebsiteSettings\\Roblox.WebsiteSettings.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Common\\Roblox.Common\\Roblox.Common.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Web\\Roblox.Web.Thumbnails\\Roblox.Web.Thumbnails.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Data\\Roblox.Data\\Roblox.Data.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Caching\\Roblox.Caching\\Roblox.Caching.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="3.7.200.10" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\Thumbnails\\Roblox.Platform.Thumbnails.Client\\Roblox.Platform.Thumbnails.Client.csproj" />
    <ProjectReference Include="..\\..\\..\\AjaxControlToolkit\\AjaxControlToolkit.csproj" />
  </ItemGroup>
</Project>