<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <AssemblyName>Roblox.Platform.TeamCreate.Client</AssemblyName>
    <LangVersion>11.0</LangVersion>
    <NoWarn>$(NoWarn);CS1668</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\..\\ApiClientBase\\Roblox.ApiClientBase\\Roblox.ApiClientBase.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\DataV2\\Core\\Roblox.DataV2.Core\\Roblox.DataV2.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>