<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.EventStream.WebEvents</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core" />
    <ProjectReference Include="..\Roblox.EventStream\Roblox.EventStream.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Time\Roblox.Time\Roblox.Time.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Common\Roblox.Common\Roblox.Common.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Collections\Roblox.Collections\Roblox.Collections.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>