<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.Email.User</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Web.ApplicationServices" />
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
      <Name>Roblox.Platform.Membership.Core</Name>
    </ProjectReference>
    <Reference Include="System.Core" />
    <ProjectReference Include="..\\..\\..\\FloodCheckers\\Roblox.FloodCheckers.Core\\Roblox.FloodCheckers.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox.Platform.Email\\Roblox.Platform.Email.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership\\Roblox.Platform.Membership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Core\\Roblox.Platform.Core\\Roblox.Platform.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox.Platform.Email.Delivery\\Roblox.Platform.Email.Delivery.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Roblox\\Roblox.BriteVerify\\Roblox.BriteVerify.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Counters\\Roblox.Platform.EphemeralCounters\\Roblox.Platform.EphemeralCounters.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Authentication\\Roblox.Platform.Authentication.AccountSecurityTickets\\Roblox.Platform.Authentication.AccountSecurityTickets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventStream\\Roblox.EventStream.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.AssetOwnership\\Roblox.Platform.AssetOwnership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\KickBox\\Roblox.Kickbox\\Roblox.Kickbox.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Translations\\Roblox.Platform.TranslationResources\\Roblox.Platform.TranslationResources.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Roblox Server Class Library\\Roblox Server Class Library.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Security\\Roblox.Platform.Security\\Roblox.Platform.Security.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventStream.WebEvents\\Roblox.EventStream.WebEvents.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Roblox\\Roblox.Entities\\Roblox.Entities.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Data\\Roblox.Data\\Roblox.Data.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Caching\\Roblox.Caching\\Roblox.Caching.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Assets\\Roblox.Assets\\Roblox.Assets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.Assets\\Roblox.Platform.Assets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Localization\\Roblox.Localization.Accounts\\Roblox.Localization.Accounts.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>