<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Amazon.Sqs</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoWarn>$(NoWarn);0618</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\\Roblox.Amazon.Core\\Roblox.Amazon.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Sentinels\\Roblox.Sentinels\\Roblox.Sentinels.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Coordination\\Roblox.Coordination\\Roblox.Coordination.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Time\\Roblox.Time\\Roblox.Time.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\FloodCheckers\\Roblox.FloodCheckers.Core\\Roblox.FloodCheckers.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\FloodCheckers\\Roblox.FloodCheckers.Redis\\Roblox.FloodCheckers.Redis.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.0" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>