<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.AbTesting</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
      <Name>Roblox.Platform.Membership.Core</Name>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Marketing\\Roblox.Marketing1\\Roblox.Platform.MarketingTodo\\Roblox.Platform.Marketing.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox.Platform.AbTesting.Core\\Roblox.Platform.AbTesting.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Core\\Roblox.Platform.Core\\Roblox.Platform.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>
