<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Sms.Client</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
