<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>Roblox.Platform.Thumbnails.Client</AssemblyName>
    <RootNamespace>Roblox.Platform.Thumbnails.Client</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>