<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.TeamCreate</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
    <NoWarn>$(NoWarn);CS1668</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\\Roblox.Platform.TeamCreate.Client\\Roblox.Platform.TeamCreate.Client.csproj" />
    <ProjectReference Include="..\\..\\Permissions\\Roblox.Platform.PermissionResolution.Client\\Roblox.Platform.PermissionResolution.Client.csproj" />
    <ProjectReference Include="..\\..\\Permissions\\Roblox.Platform.Permissions.Client\\Roblox.Platform.Permissions.Client.csproj" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Serialization" />
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\CloudEdit\\Roblox.Platform.CloudEdit.Permissions\\Roblox.Platform.CloudEdit.Permissions.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox.Platform.TeamCreate.Notifications\\Roblox.Platform.TeamCreate.Notifications.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership\\Roblox.Platform.Membership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Universes\\Roblox.Platform.Universes\\Roblox.Platform.Universes.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\ApiClientBase\\Roblox.ApiClientBase\\Roblox.ApiClientBase.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Core\\Roblox.Platform.Core\\Roblox.Platform.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\DataV2\\Core\\Roblox.DataV2.Core\\Roblox.DataV2.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Social\\Roblox.Platform.Social\\Roblox.Platform.Social.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Games\\Roblox.Platform.Games.Client\\Roblox.Platform.Games.Client.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.Assets\\Roblox.Platform.Assets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Games\\Roblox.Platform.GameInstances\\Roblox.Platform.GameInstances.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Presence\\Roblox.Platform.Presence\\Roblox.Platform.Presence.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Games\\Roblox.Platform.Games\\Roblox.Platform.Games.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.AssetPermissions\\Roblox.Platform.AssetPermissions.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Assets\\Roblox.Platform.AssetsCore\\Roblox.Platform.AssetsCore.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Permissions\\Roblox.Platform.Permissions\\Roblox.Platform.Permissions.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Amazon\\Roblox.Amazon.Sns\\Roblox.Amazon.Sns.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.500.17" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
</Project>