<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.Membership</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web.ApplicationServices" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\Core\\Roblox.Platform.Core\\Roblox.Platform.Core.csproj" />
    <ProjectReference Include="..\\..\\..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj" />
    <ProjectReference Include="..\\..\\..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj" />
    <ProjectReference Include="..\\..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj" />
    <ProjectReference Include="..\\..\\..\\Common\\Roblox.Common\\Roblox.Common.csproj" />
    <ProjectReference Include="..\\..\\..\\Caching\\Roblox.Caching\\Roblox.Caching.csproj" />
    <ProjectReference Include="..\\..\\..\\Hashing\\Roblox.Hashing\\Roblox.Hashing.csproj" />
    <ProjectReference Include="..\\..\\Users\\Roblox.Platform.Users.Client\\Roblox.Platform.Users.Client.csproj" />
    <ProjectReference Include="..\\..\\Users\\Roblox.Platform.Users\\Roblox.Platform.Users.csproj" />
    <ProjectReference Include="..\\..\\..\\Passwords\\Roblox.Passwords.Client\\Roblox.Passwords.Client.csproj" />
    <ProjectReference Include="..\\..\\..\\Amazon\\Roblox.Amazon.Sns\\Roblox.Amazon.Sns.csproj" />
    <ProjectReference Include="..\\..\\..\\Amazon\\Roblox.Amazon.Core\\Roblox.Amazon.Core.csproj" />
    <ProjectReference Include="..\\..\\..\\Random\\Roblox.Random\\Roblox.Random.csproj" />
    <ProjectReference Include="..\\..\\..\\Roblox\\Roblox.Entities\\Roblox.Entities.csproj" />
    <ProjectReference Include="..\\..\\..\\Data\\Roblox.Data\\Roblox.Data.csproj" />
    <ProjectReference Include="..\\..\\Premium\\Roblox.Platform.PremiumFeatures\\Roblox.Platform.PremiumFeatures.csproj" />
    <ProjectReference Include="..\\..\\Premium\\Roblox.Platform.PremiumFeatures\\Roblox.Platform.PremiumFeatures.csproj" />
    <ProjectReference Include="..\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj" />
  </ItemGroup>
</Project>