<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.LiveGamer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Roblox.Billing\Roblox.Billing.csproj" />
    <ProjectReference Include="..\Configuration\Roblox.Configuration\Roblox.Configuration.csproj" />
  </ItemGroup>
</Project>