<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Web.Code</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Core" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="WebMarkupMin.Core" Version="2.12.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.300.27" />
    <PackageReference Include="AjaxMin" Version="5.14.5506.26202" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Core\Roblox.Platform.Core\Roblox.Platform.Core.csproj" />
    <ProjectReference Include="..\..\Platform\Membership\Roblox.Platform.Membership\Roblox.Platform.Membership.csproj" />
    <ProjectReference Include="..\..\Web\Roblox.Web.Devices\Roblox.Web.Devices.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Presence\Roblox.Platform.Presence.csproj" />
    <ProjectReference Include="..\..\Roblox.EphemeralCounters\Roblox.EphemeralCounters.csproj" />
    <ProjectReference Include="..\..\Roblox.FloodCheckers\Roblox.FloodCheckers.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Devices\Roblox.Platform.Devices.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Universes\Roblox.Platform.Universes.csproj" />
    <ProjectReference Include="..\..\Users\Roblox.Users\Roblox.Users.csproj" />
    <ProjectReference Include="..\..\Web\Roblox.Web\Roblox.Web.csproj" />
    <ProjectReference Include="..\..\Common\Roblox.Common\Roblox.Common.csproj" />
    <ProjectReference Include="..\..\Common\Roblox.Common.Web\Roblox.Common.Web.csproj" />
    <ProjectReference Include="..\..\Configuration\Roblox.Configuration\Roblox.Configuration.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Captcha\Roblox.Platform.Captcha.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.AssetPermissions\Roblox.Platform.AssetPermissions.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Assets\Roblox.Platform.Assets.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.AssetsCore\Roblox.Platform.AssetsCore.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Marketing\Roblox.Platform.Marketing.csproj" />
    <ProjectReference Include="..\..\Platform\Authentication\Roblox.Platform.Authentication\Roblox.Platform.Authentication.csproj" />
    <ProjectReference Include="..\..\EventLog\Roblox.EventLog\Roblox.EventLog.csproj" />
    <ProjectReference Include="..\..\Platform\Security\Roblox.Platform.Security\Roblox.Platform.Security.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Demographics\Roblox.Platform.Demographics.csproj" />
    <ProjectReference Include="..\..\Roblox.RequestContext\Roblox.RequestContext.csproj" />
    <ProjectReference Include="..\..\Web\Roblox.Web.Presence\Roblox.Web.Presence.csproj" />
    <ProjectReference Include="..\..\TranslationResources\Roblox.TranslationResources\Roblox.TranslationResources.csproj" />
    <ProjectReference Include="..\Roblox.Web.Authentication\Roblox.Web.Authentication.csproj" />
    <ProjectReference Include="..\..\ApiClientBase\Roblox.ApiClientBase\Roblox.ApiClientBase.csproj" />
    <ProjectReference Include="..\..\Platform\Membership\Roblox.Platform.Membership.Core\Roblox.Platform.Membership.Core.csproj" />
    <ProjectReference Include="..\..\Platform\Membership\Roblox.Platform.Membership.Extensions\Roblox.Platform.Membership.Extensions.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Localization.Core\Roblox.Platform.Localization.Core.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Localization.Accounts\Roblox.Platform.Localization.Accounts.csproj" />
    <ProjectReference Include="..\..\Roblox.Random\Roblox.Random.csproj" />
    <ProjectReference Include="..\..\Roblox.Games.Client\Roblox.Games.Client.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Avatar\Roblox.Platform.Avatar.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.EventStream\Roblox.Platform.EventStream.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.EventStream.WebEvents\Roblox.Platform.EventStream.WebEvents.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.IpAddresses\Roblox.Platform.IpAddresses.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Infrastructure\Roblox.Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.GameInstances\Roblox.Platform.GameInstances.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Games\Roblox.Platform.Games.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.UserSetting\Roblox.Platform.UserSetting.csproj" />
    <ProjectReference Include="..\..\Roblox.Marketing\Roblox.Marketing.csproj" />
    <ProjectReference Include="..\..\Roblox.TextFilter.Client\Roblox.TextFilter.Client.csproj" />
    <ProjectReference Include="..\Roblox.Web.Metrics\Roblox.Web.Metrics.csproj" />
    <ProjectReference Include="..\..\Roblox.AuthenticationV2\Roblox.AuthenticationV2.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Social\Roblox.Platform.Social.csproj" />
    <ProjectReference Include="..\..\Caching\Roblox.Caching\Roblox.Caching.csproj" />
    <ProjectReference Include="..\..\Roblox.Locking\Roblox.Locking.csproj" />
    <ProjectReference Include="..\..\Instrumentation\Roblox.Instrumentation\Roblox.Instrumentation.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Party\Roblox.Platform.Party.csproj" />
    <ProjectReference Include="..\..\Roblox.RealTimeNotifications\Roblox.RealTimeNotifications.csproj" />
    <ProjectReference Include="..\..\Roblox.RealTimeNotifications.Client\Roblox.RealTimeNotifications.Client.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.AbTesting\Roblox.Platform.AbTesting.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.AbTesting.Core\Roblox.Platform.AbTesting.Core.csproj" />
    <ProjectReference Include="..\..\Roblox.Gigya\Roblox.Gigya.csproj" />
    <ProjectReference Include="..\..\Roblox.Networking\Roblox.Networking.csproj" />
    <ProjectReference Include="..\..\Roblox.Platform.Counters\Roblox.Platform.Counters.csproj" />
    <ProjectReference Include="..\..\Roblox.Marketplace.Client\Roblox.Marketplace.Client.csproj" />
    <ProjectReference Include="..\..\Roblox.Amazon.Sns\Roblox.Amazon.Sns.csproj" />
  </ItemGroup>
</Project>