<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.VirtualCurrency</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
    <NoWarn>$(NoWarn);CS1668</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <ProjectReference Include="..\\..\\Currency\\Roblox.Platform.Currency.Client\\Roblox.Platform.Currency.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\\..\\Membership\\Roblox.Platform.Membership.Core\\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\Core\\Roblox.Platform.Core\\Roblox.Platform.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\..\\..\\Sentinels\\Roblox.Sentinels\\Roblox.Sentinels.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>
</Project>