<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Platform.Permissions</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS1668;1668</NoWarn>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Roblox.Platform.Permissions.Client\Roblox.Platform.Permissions.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <ProjectReference Include="..\..\Membership\Roblox.Platform.Membership.Core\Roblox.Platform.Membership.Core.csproj">
      <Project>
      </Project>
      <Name>Roblox.Platform.Membership.Core</Name>
    </ProjectReference>
    <Reference Include="System.Web.ApplicationServices" />
    <ProjectReference Include="..\Roblox.Platform.Permissions.Core\Roblox.Platform.Permissions.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Membership\Roblox.Platform.Membership\Roblox.Platform.Membership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\CallContext\Roblox.Platform.CallContext\Roblox.Platform.CallContext.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Events\Roblox.EventLog\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ApiClientBase\Roblox.ApiClientBase\Roblox.ApiClientBase.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Demographics\Roblox.Platform.Demographics\Roblox.Platform.Demographics.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Localization\Roblox.Localization.Accounts\Roblox.Localization.Accounts.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Social\Roblox.Platform.Social\Roblox.Platform.Social.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Groups\Roblox.Platform.Groups\Roblox.Platform.Groups.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Authentication\Roblox.Platform.Authentication\Roblox.Platform.Authentication.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Configuration\Roblox.Configuration\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Core\Roblox.Platform.Core\Roblox.Platform.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Moderation\Roblox.Moderation\Roblox.Moderation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Caching\Roblox.Caching\Roblox.Caching.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Data\Roblox.Data\Roblox.Data.csproj">
      <Project>
      </Project>
    </ProjectReference>
  </ItemGroup>
</Project>
