<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.Economy</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
    <NoWarn>$(NoWarn);1668;0618</NoWarn>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Roblox.Data">
      <HintPath>..\..\Website\bin\Roblox.Data.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.Caching">
      <HintPath>..\..\Website\bin\Roblox.Caching.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="Roblox.Configuration">
      <HintPath>..\..\Website\bin\Roblox.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.Economy.Common">
      <HintPath>..\..\Website\bin\Roblox.Economy.Common.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.Common">
      <HintPath>..\..\Website\bin\Roblox.Common.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.EventLog">
      <HintPath>..\..\Website\bin\Roblox.EventLog.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.MssqlDatabases">
      <HintPath>..\..\Website\bin\Roblox.MssqlDatabases.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>