<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>Roblox.Thumbnails.Client</AssemblyName>
    <RootNamespace>Roblox.Thumbnails.Client</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Roblox.EventLog">
      <HintPath>..\..\Website\bin\Roblox.EventLog.dll</HintPath>
    </Reference>
    <Reference Include="Roblox.Instrumentation">
      <HintPath>..\..\Website\bin\Roblox.Instrumentation.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
