<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox Server Class Library</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>Roblox</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="Roblox.Roles.Client" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Data" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="Roblox.Groups.Client" />
    <ProjectReference Include="..\\Data\\Roblox.Data\\Roblox.Data.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Caching\\Roblox.Caching\\Roblox.Caching.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Common\\Roblox.Common\\Roblox.Common.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Amazon\\Roblox.Amazon.Sqs\\Roblox.Amazon.Sqs.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox\\Roblox.BucketStore\\Roblox.BucketStore.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Events\\Roblox.EventLog\\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Assets\\Roblox.Platform.AssetOwnership\\Roblox.Platform.AssetOwnership.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Locking\\Roblox.Locking\\Roblox.Locking.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Amazon\\Roblox.Amazon\\Roblox.Amazon.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Common\\Roblox.Common.Web\\Roblox.Common.Web.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Mssql\\Roblox.MssqlDatabases\\Roblox.MssqlDatabases.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Marketplace\\Roblox.Platform.Marketplace.Client\\Roblox.Platform.Marketplace.Client.csproj" />
    <ProjectReference Include="..\\Economy\\Roblox.Economy.Common\\Roblox.Economy.Common.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Economy\\Roblox.Economy\\Roblox.Economy.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Configuration\\Roblox.Configuration\\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Passwords\\Roblox.Passwords.Client\\Roblox.Passwords.Client.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Users\\Roblox.Platform.Users.Client\\Roblox.Platform.Users.Client.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Moderation\\Roblox.Moderation\\Roblox.Moderation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\DataV2\\Core\\Roblox.DataV2.Core\\Roblox.DataV2.Core.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\ApiClientBase\\Roblox.ApiClientBase\\Roblox.ApiClientBase.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Agents\\Roblox.Agents\\Roblox.Agents.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Instrumentation\\Roblox.Instrumentation\\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Roblox\\Roblox.Entities.Mssql\\Roblox.Entities.Mssql.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\RequestContext\\Roblox.RequestContext\\Roblox.RequestContext.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Assets\\Roblox.Assets\\Roblox.Assets.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Redis\\Roblox.Redis.Lru\\Roblox.Redis.Lru.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Redis\\Roblox.Redis\\Roblox.Redis.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Users\\Roblox.Platform.Users\\Roblox.Platform.Users.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Coordination\\Roblox.Coordination\\Roblox.Coordination.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Users\\Roblox.Platform.UserCacheMigrationSettings\\Roblox.Platform.UserCacheMigrationSettings.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\\Platform\\Content\\Roblox.Platform.ContentRatings\\Roblox.Platform.ContentRatings.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.6.66" />
  </ItemGroup>
</Project>