<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.EventStream</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <ProjectReference Include="..\..\Amazon\Roblox.Amazon.Firehose\Roblox.Amazon.Firehose.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\Roblox.EventLog\Roblox.EventLog.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Collections\Roblox.Collections\Roblox.Collections.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Random\Roblox.Random\Roblox.Random.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Instrumentation\Roblox.Instrumentation\Roblox.Instrumentation.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Configuration\Roblox.Configuration\Roblox.Configuration.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <ProjectReference Include="..\..\Coordination\Roblox.Coordination\Roblox.Coordination.csproj">
      <Project>
      </Project>
    </ProjectReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.500.11" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
</Project>