<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Roblox.OwnershipV2.Client</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <NoWarn>$(NoWarn);CS0618;CS1668</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataV2\Core\Roblox.DataV2.Core\Roblox.DataV2.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Roblox.ApiClientBase">
      <HintPath>..\..\Website\bin\Roblox.ApiClientBase.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
