<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>AjaxControlToolkit</AssemblyName>
    <RootNamespace>AjaxControlToolkit</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>
</Project>
